# Generated by Django 5.0.6 on 2024-12-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
